version: '3.8'
services:
  # Backend service
  backend:
    build: ./backend
    deploy:
      replicas: 3
    environment:
      - SERVICE_NAME=backend
    networks:
      - app-network

  # Frontend service
  frontend:
    build: ./frontend
    deploy:
      replicas: 5
    ports:
      - "3001-3005:3001"  # Expose ports outside 3001 to 3005 -> routes to 3001 on the container
    depends_on:
      - backend
      - nginx
    environment:
      - SERVICE_NAME=frontend
      - BACKEND_URL=http://nginx:80
    networks:
      - app-network

  # Load balancer dla backend
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge