version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # really in /var/lib/docker/volumes
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro # read-only

  backend:
    build: ./backend
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=example
      - PGDATABASE=postgres
      - PGPORT=5432
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres-data: