version: '3.8'

services:
  division-api:
    image: division-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/divide/1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s