version: '3.8'
services:
  service_a:
    build: ./service_a
    ports:
      - "3000:3000"
  service_b:
    build: ./service_b
    ports:
      - "3001:3001"
    depends_on:
      - service_a
